converter:
  # Input file formats supported
  input_formats:
    - "docx"
    - "doc"
    - "odt"
    - "rtf"
    - "txt"
    - "xlsx"
    - "xls"
    - "ods"
    - "pptx"
    - "ppt"
    - "odp"
  
  # Output format for conversion
  output_format: "pdf"
  
  # Number of parallel workers
  workers: 4
  
  # Temporary directory for processing
  temp_dir: "/tmp/converter"
  
  # Maximum file size in MB
  max_file_size: 100
  
  # Timeout for conversion in seconds
  conversion_timeout: 300

server:
  host: "0.0.0.0"
  port: 8000
  debug: false